# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lge/sm8250-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter timelm,$(TARGET_DEVICE)),)

endif
